blog_app/models.py
from datetime import datetime
from flask_login import UserMixin
from blog_app import db, login_manager


@login_manager.user_loader
def load_user(user_id):
    return User.query.get(int(user_id))


class Post(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    title = db.Column(db.String(100), nullable=False)
    content = db.Column(db.Text, nullable=False)
    created_at = db.Column(db.DateTime, nullable=False,
                           default=datetime.utcnow)
    user_id = db.Column(db.Integer, db.ForeignKey('user.id'), nullable=False)

    def __str__(self):
        return self.title


class User(db.Model, UserMixin):
    id = db.Column(db.Integer, primary_key=True)
    email = db.Column(db.String(100), unique=True, nullable=False)
    username = db.Column(db.String(20), unique=True, nullable=False)
    password = db.Column(db.String(60), nullable=False)
    posts = db.relationship('Post', backref='author', lazy=True)

    def __str__(self):
        return self.username

blog_app/posts/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField
from wtforms.fields.simple import TextAreaField
from wtforms.validators import DataRequired


class PostForm(FlaskForm):
    title = StringField('Title*', validators=[DataRequired()])
    content = TextAreaField('Content*', validators=[DataRequired()])
    submit = SubmitField('Post')


class DeletePostForm(FlaskForm):
    pass

blog_app/users/forms.py
from flask_wtf import FlaskForm
from wtforms import PasswordField, StringField, SubmitField
from wtforms.validators import DataRequired, Email, EqualTo, Length, ValidationError
from blog_app.models import User


class UserRegistrationForm(FlaskForm):
    email = StringField('Email*', validators=[DataRequired(), Email()])
    username = StringField('Username*', validators=[
                           DataRequired(), Length(min=2, max=20)])
    password1 = PasswordField('Password*', validators=[DataRequired()])
    password2 = PasswordField('Password confirmation*', validators=[
                              DataRequired(), EqualTo('password1', 'Passwords have to match.')])
    submit = SubmitField('Register')

    def validate_email(self, email):
        user = User.query.filter_by(email=email.data).first()
        if user:
            raise ValidationError('That email is already taken.')

    def validate_username(self, username):
        user = User.query.filter_by(username=username.data).first()
        if user:
            raise ValidationError('That username is already taken.')


class UserLoginForm(FlaskForm):
    username = StringField('Username*', validators=[DataRequired()])
    password = PasswordField('Password*', validators=[DataRequired()])
    submit = SubmitField('Login')

blog_app/__init__.py
from flask import Flask, redirect
from flask_bcrypt import Bcrypt
from flask_login import LoginManager
from flask_sqlalchemy import SQLAlchemy
from blog_app.config import Config


bcrypt = Bcrypt()
db = SQLAlchemy()
login_manager = LoginManager()
login_manager.login_view = 'users.login'
login_manager.login_message_category = 'info'


def create_app(config_class=Config):
    app = Flask(__name__)
    app.config.from_object(config_class)

    bcrypt.init_app(app)
    db.init_app(app)
    login_manager.init_app(app)

    from blog_app.posts.routes import posts
    from blog_app.users.routes import users
    app.register_blueprint(posts, url_prefix='/posts')
    app.register_blueprint(users, url_prefix='/users')

    @app.route('/')
    def _():
        return redirect('posts')

    return app

blog_app/posts/routes.py
from flask import abort, Blueprint, flash, redirect, render_template, request, url_for
from flask_login import current_user, login_required
from blog_app import db
from blog_app.models import Post
from blog_app.posts.forms import DeletePostForm, PostForm

posts = Blueprint('posts', __name__)


@posts.route('/')
def index():
    return redirect('list')


@posts.route('/list')
@login_required
def list():
    posts = Post.query.order_by(Post.created_at.desc())
    return render_template('posts/post_list.html', posts=posts)


@posts.route('<int:pk>/')
@login_required
def detail(pk):
    post = Post.query.get_or_404(pk)
    return render_template('posts/post_detail.html', post=post)


@posts.route('create/', methods=['GET', 'POST'])
@login_required
def create():
    form = PostForm()
    if form.validate_on_submit():
        post = Post(title=form.title.data,
                    content=form.content.data, author=current_user)
        db.session.add(post)
        db.session.commit()
        flash('Your post has been created.', 'success')
        return redirect(url_for('posts.detail', pk=post.id))
    return render_template('posts/post_form.html', form=form)


@posts.route('<int:pk>/update/', methods=['GET', 'POST'])
@login_required
def update(pk):
    post = Post.query.get_or_404(pk)
    if post.author != current_user:
        abort(403)
    form = PostForm(title=post.title, content=post.content)
    if form.validate_on_submit():
        post.title = form.title.data
        post.content = form.content.data
        db.session.commit()
        flash('Your post has been updated.', 'success')
        return redirect(url_for('posts.detail', pk=post.id))
    return render_template('posts/post_form.html', form=form)


@posts.route('<int:pk>/delete/', methods=['GET', 'POST'])
@login_required
def delete(pk):
    post = Post.query.get_or_404(pk)
    form = DeletePostForm()
    if post.author != current_user:
        abort(403)
    if request.method == 'POST':
        db.session.delete(post)
        db.session.commit()
        flash('Your post has been deleted.', 'success')
        return redirect(url_for('posts.index'))
    return render_template('posts/post_confirm_delete.html', form=form, post=post)

blog_app/users/routes.py
from flask import Blueprint, flash, redirect, render_template, request, url_for
from flask_login import current_user, login_required, login_user, logout_user
from blog_app import bcrypt, db
from blog_app.models import User
from blog_app.users.forms import UserLoginForm, UserRegistrationForm

users = Blueprint('users', __name__)


@users.route('/')
def index():
    return redirect('profile')


@users.route('profile/')
@login_required
def profile():
    return render_template('users/user_profile.html')


@users.route('register/', methods=['GET', 'POST'])
def register():
    if current_user.is_authenticated:
        return redirect(url_for('posts.index'))

    form = UserRegistrationForm()
    if form.validate_on_submit():
        hashed_password = bcrypt.generate_password_hash(
            form.password1.data).decode('utf-8')
        user = User(email=form.email.data,
                    username=form.username.data, password=hashed_password)
        db.session.add(user)
        db.session.commit()
        flash('Your account has been created.', 'success')
        return redirect(url_for('users.login'))
    return render_template('users/user_register.html', form=form)


@users.route('login/', methods=['GET', 'POST'])
def login():
    if current_user.is_authenticated:
        return redirect(url_for('posts.index'))

    form = UserLoginForm()
    if form.validate_on_submit():
        user = User.query.filter_by(username=form.username.data).first()
        if user and bcrypt.check_password_hash(user.password, form.password.data):
            login_user(user, remember=True)
            next_page = request.args.get('next')
            return redirect(next_page) if next_page else redirect(url_for('posts.index'))
        else:
            flash('You have entered wrong credentials.', 'danger')
    return render_template('users/user_login.html', form=form)


@users.route('logout/')
def logout():
    logout_user()
    return render_template('users/user_logout.html')

blog_app/templates/base.html
<!DOCTYPE html>
<html lang="en" class="h-100">
    <head>
        <meta charset="UTF-8" />
        <meta http-equiv="X-UA-Compatible" content="IE=edge" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />

        <link
            href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css"
            rel="stylesheet"
            integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3"
            crossorigin="anonymous"
        />
        <link href="{{ url_for('static', filename='main.css') }}" rel="stylesheet" type="text/css" />

        <title>Flask Blog App</title>
    </head>
    <body class="d-flex flex-column h-100">
        <header class="bg-dark">
            <nav class="navbar navbar-expand navbar-dark">
                <a class="navbar-brand px-4" href="{{ url_for('posts.index') }}">Home</a>
                <div class="navbar-nav ms-auto px-4">
                    {% if current_user.is_authenticated %}
                    <a class="nav-link" href="{{ url_for('posts.create') }}">New Post</a>
                    <a class="nav-link" href="{{ url_for('users.profile') }}">Profile</a>
                    <a class="nav-link" href="{{ url_for('users.logout') }}">Logout</a>
                    {% else %}
                    <a class="nav-link" href="{{ url_for('users.register') }}">Register</a>
                    <a class="nav-link" href="{{ url_for('users.login') }}">Login</a>
                    {% endif %}
                </div>
            </nav>
        </header>
        <main class="container" style="max-width: 800px">
            <div class="m-4">
                {% with messages = get_flashed_messages(with_categories=true) %} {% if messages %} {% for category,
                message in messages %}
                <div class="alert alert-{{ category }}">{{ message }}</div>
                {% endfor %} {% endif %} {% endwith %} {% block content %} {% endblock content %}
            </div>
        </main>
        <footer class="bg-dark mt-auto py-2">
            <div class="text-center text-muted">&copy; 2021 - Stefan Eyerer</div>
        </footer>

        <script
            src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"
            integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p"
            crossorigin="anonymous"
        ></script>
    </body>
</html>

blog_app/templates/posts/post_confirm_delete.html
{% extends 'base.html' %} {% block content %}
<h4 class="border-bottom">Delete Post</h4>
<form method="POST">
    {{ form.hidden_tag() }}
    <h5 class="mt-4">Are you sure you want to delete post "{{ post.title }}"?</h5>
    <div class="mt-4">
        <button class="btn btn-outline-danger" type="submit">Delete</button>
        <a class="btn btn-outline-secondary" href="{{ url_for('posts.detail', pk=post.id) }}">Cancel</a>
    </div>
</form>
{% endblock content %}

blog_app/templates/posts/post_detail.html
{% extends 'base.html' %} {% block content %}
<h4 class="border-bottom">Post Detail</h4>
<article class="card mt-4">
    <div class="card-header d-flex align-items-center justify-content-between">
        <div>
            <span class="h6">Author: {{ post.author }}</span>
            <small class="text-muted ps-2">{{ post.created_at.strftime('%B %d, %Y') }}</small>
        </div>
        {% if post.author == current_user %}
        <div>
            <a class="btn btn-secondary btn-sm" href="{{ url_for('posts.update', pk=post.id) }}">Update</a>
            <a class="btn btn-danger btn-sm" href="{{ url_for('posts.delete', pk=post.id) }}">Delete</a>
        </div>
        {% endif %}
    </div>
    <div class="card-body">
        <h5 class="card-title">{{ post.title }}</h5>
        <p class="card-text">{{ post.content }}</p>
    </div>
</article>
{% endblock content %}

blog_app/templates/posts/post_form.html
{% extends 'base.html' %} {% block content %}
<h4 class="border-bottom">Post</h4>
<form method="POST">
    {{ form.hidden_tag() }}
    <fieldset>
        <div class="mb-3">
            {{ form.title.label(class="form-control-label") }} {% if form.title.errors %} {{
            form.title(class="form-control is-invalid") }}
            <div class="invalid-feedback">
                {% for error in form.title.errors %}
                <span>{{ error }}</span>
                {% endfor %}
            </div>
            {% else %} {{ form.title(class="form-control") }} {% endif %}
        </div>
        <div class="mb-3">
            {{ form.content.label(class="form-control-label") }} {% if form.content.errors %} {{
            form.content(class="form-control is-invalid") }}
            <div class="invalid-feedback">
                {% for error in form.content.errors %}
                <span>{{ error }}</span>
                {% endfor %}
            </div>
            {% else %} {{ form.content(class="form-control") }} {% endif %}
        </div>
    </fieldset>
    <button class="btn btn-outline-info mb-3" type="submit">Post</button>
</form>
{% endblock content %}

blog_app/templates/posts/post_list.html
{% extends 'base.html' %} {% block content %}
<h4 class="border-bottom">Post List</h4>
{% for post in posts %}
<article class="card mt-4">
    <div class="card-header">
        <span class="h6">Author: {{ post.author }}</span>
        <small class="text-muted ps-2">{{ post.created_at.strftime('%B %d, %Y') }}</small>
    </div>
    <div class="card-body">
        <h5 class="card-title">
            <a href="{{ url_for('posts.detail', pk=post.id) }}">{{ post.title }}</a>
        </h5>
        <p class="card-text">{{ post.content }}</p>
    </div>
</article>
{% else %}
<span>No posts were posted yet.</span>
{% endfor %} {% endblock content %}

blog_app/templates/users/user_login.html
{% extends 'base.html' %} {% block content %}
<h4 class="border-bottom">Login</h4>
<form method="POST">
    {{ form.hidden_tag() }}
    <fieldset>
        <div class="mb-3">
            {{ form.username.label(class="form-label") }} {% if form.username.errors %} {{
            form.username(class="form-control is-invalid") }}
            <div class="invalid-feedback">
                {% for error in form.username.errors %}
                <span>{{ error }}</span>
                {% endfor %}
            </div>
            {% else %} {{ form.username(class="form-control") }} {% endif %}
        </div>
        <div class="mb-3">
            {{ form.password.label(class="form-label") }} {% if form.password.errors %} {{
            form.password(class="form-control is-invalid") }}
            <div class="invalid-feedback">
                {% for error in form.password.errors %}
                <span>{{ error }}</span>
                {% endfor %}
            </div>
            {% else %} {{ form.password(class="form-control") }} {% endif %}
        </div>
    </fieldset>
    {{ form.submit(class="btn btn-outline-info mb-3") }}
</form>
<div class="border-top pt-2">
    <small class="text-muted">
        Need an account? <a class="ml-2" href="{{ url_for('users.register') }}">Register</a>
    </small>
</div>
{% endblock content %}

blog_app/templates/users/user_logout.html
{% extends 'base.html' %} {% block content %}
<h4 class="border-bottom">Logout</h4>
<h5 class="mt-4">You have been logged out.</h5>
<small class="text-muted">
    <a href="{{ url_for('users.login') }}">Back to Login</a>
</small>
{% endblock content %}

blog_app/templates/users/user_profile.html
{% extends 'base.html' %} {% block content %}
<h4 class="border-bottom">Profile</h4>
<div class="card mt-4">
    <div class="card-header">
        <h5>User Info</h5>
    </div>
    <div class="card-body">
        <h6 class="card-text">Username: <span>{{ current_user.username }}</span></h6>
        <h6 class="card-text">Email: <span>{{ current_user.email }}</span></h6>
        <p class="card-text">
            <small class="text-muted">Currently you cannot edit your profile.</small>
        </p>
    </div>
</div>
{% endblock content %}

blog_app/templates/users/user_register.html
{% extends 'base.html' %} {% block content %}
<h4 class="border-bottom">Register</h4>
<form method="POST">
    {{ form.hidden_tag() }}
    <fieldset>
        <div class="mb-3">
            {{ form.username.label(class="form-label") }} {% if form.username.errors %} {{
            form.username(class="form-control is-invalid") }}
            <div class="invalid-feedback">
                {% for error in form.username.errors %}
                <span>{{ error }}</span>
                {% endfor %}
            </div>
            {% else %} {{ form.username(class="form-control") }} {% endif %}
        </div>
        <div class="mb-3">
            {{ form.email.label(class="form-label") }} {% if form.email.errors %} {{ form.email(class="form-control
            is-invalid") }}
            <div class="invalid-feedback">
                {% for error in form.email.errors %}
                <span>{{ error }}</span>
                {% endfor %}
            </div>
            {% else %} {{ form.email(class="form-control") }} {% endif %}
        </div>
        <div class="mb-3">
            {{ form.password1.label(class="form-label") }} {% if form.password1.errors %} {{
            form.password1(class="form-control is-invalid") }}
            <div class="invalid-feedback">
                {% for error in form.password1.errors %}
                <span>{{ error }}</span>
                {% endfor %}
            </div>
            {% else %} {{ form.password1(class="form-control") }} {% endif %}
        </div>
        <div class="mb-3">
            {{ form.password2.label(class="form-label") }} {% if form.password2.errors %} {{
            form.password2(class="form-control is-invalid") }}
            <div class="invalid-feedback">
                {% for error in form.password2.errors %}
                <span>{{ error }}</span>
                {% endfor %}
            </div>
            {% else %} {{ form.password2(class="form-control") }} {% endif %}
        </div>
    </fieldset>
    {{ form.submit(class="btn btn-outline-info mb-3") }}
</form>
<div class="border-top pt-2">
    <small class="text-muted">
        Already have an account? <a class="ml-2" href="{{ url_for('users.login') }}">Login</a>
    </small>
</div>
{% endblock content %}